name: CI-Deploy

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  deploy-contracts:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'CI:Deploy')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Start Geth Devnet
        run: |
          docker compose up -d
          echo "Waiting for Geth JSON-RPC..."
          until curl -s http://localhost:8545; do sleep 1; done

      - name: Install Node Modules
        working-directory: ./hardhat
        run: npm ci

      - name: Compile Contracts
        working-directory: ./hardhat
        run: npx hardhat compile

      - name: Deploy Contracts
        working-directory: ./hardhat
        run: npx hardhat run scripts/deploy.ts --network localhost

