name: Task workflow


on:
  pull_request:
    types: [ closed ]
    branches: [ master ]


jobs:
  build:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'CI:Build')
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: echo label
        run: echo "PR with label 'CI:Build' was merged"